###
GET http://localhost:3000/tampilkanlomba

###
GET http://localhost:3000/tampilkanlombabyid/66dedd21e17a1c4498bca8f5

###
DELETE http://localhost:3000/hapus

###
DELETE http://localhost:3000/hapus/66f23844aeb8e0c947f08ef1
