###
GET http://localhost:3000/tampilkanlomba

###
POST http://localhost:3000/tambahlomba
Content-Type: application/json

{
  "nama": "Lomba Cipta Puisi",
  "penyelenggara": "Fakultas Ekonomi Dan Bisnis Islam UIN Alauddin Makassar",
  "deadline": "25 November 2018",
  "pendaftaran": "gratis",
  "tingkat": "",
  "kategori": "Puisi",
  "peserta": "SMA Sederajat",
  "poster": "lombaPuisi.jpg",
  "deskripsi": "Lomba cipta puisi festifal ekonomi 2018"
}

###
DELETE http://localhost:3000/hapus/66dece6ee17a1c4498bca8f1