###
GET http://localhost:3000/tampilkanlomba

###
POST http://localhost:3000/tambahlomba
Content-Type: application/json

{
  "nama": "Lomba Web Development Nasional",
  "penyelenggara": "Kominfo",
  "deadline": "15 September 2024",
  "pendaftaran": "berbayar",
  "tingkat": "Nasional",
  "kategori": "Cyber Security",
  "peserta": "Mahasiswa",
  "poster": "lomba.png",
  "deskripsi": "Lomba Cyber Nasional, hanya untuk Mahasiswa se-Indonesia"
}

###
DELETE http://localhost:3000/hapus/66de93425d580543b8c34fa5